controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true
    
    diff_cont:
      type: "diff_drive_controller/DiffDriveController"
    
    joint_broad:
      type: "joint_state_broadcaster/JointStateBroadcaster"
    

diff_cont:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]


    cmd_vel_timeout: 100.0
    publish_rate: 100.0

    wheel_separation: 0.23
    wheel_radius: 0.05

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # use_stamped_vel: false
    # enable_stamped_cmd_vel: false
    enable_odom_tf: true
    odom_frame_id: "odom"
    base_frame_id: "base_link"


    # odom_frame_id: odom
    # base_frame_id: base_link
    # pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    # twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # position_feedback: false
    # open_loop: true

    # cmd_vel_timeout: 0.5 # seconds
    # publish_limited_velocity: true
    # velocity_rolling_window_size: 10

    # linear.x.max_velocity: .NAN
    # linear.x.min_velocity: .NAN
    # linear.x.max_acceleration: .NAN
    # linear.x.max_deceleration: .NAN
    # linear.x.max_acceleration_reverse: .NAN
    # linear.x.max_deceleration_reverse: .NAN
    # linear.x.max_jerk: .NAN
    # linear.x.min_jerk: .NAN

    # angular.z.max_velocity: .NAN
    # angular.z.min_velocity: .NAN
    # angular.z.max_acceleration: .NAN
    # angular.z.max_deceleration: .NAN
    # angular.z.max_acceleration_reverse: .NAN
    # angular.z.max_deceleration_reverse: .NAN
    # angular.z.max_jerk: .NAN
    # angular.z.min_jerk: .NAN